### ISSUE TITLE
Hide messages button conditionally

### ISSUE THREAD

**Issue by thediary** [smooch/smooch-helpkit-ios#6]
Hi there,

I think support should be added to allow for conditional hiding of the send a message button. Our current use case for the extension is to provide a help desk to all of our users, but we'd like to only allow them to send a message and enter the smooch "message center" if they are a paid subscriber to our app.

Is this something you could look at adding, or at least would be open to a pull request for (though I think it would be a rather quick implementation that you should have time to include and push out a new cocoapods update.)

Thanks!

**Comment by gozman** [comment]
We've considered doing this but decided against it because of how users expect mobile messaging to work. When a user messages you, they don't generally have an expectation of an immediate response - just as when they message their friends with iMessage or whatever else. When you answer them, they'll get a notification and will come back to your app.

To further set expectations around response time, you can try using an auto-response whisper to be able to notify your users about how long a reply might take.

That said, you're free to fork the branch and add in this logic for yourself in your own app. However, we won't be merging this back into the core product.

Let me know if there's any other way I can help!

Mike

**Comment by gozman** [comment]
This is embarrassing :)

When I replied to your message, I confused it with another in my inbox and didn't address it properly. 

We'll certainly add a conditional option to the send messages button so that you can do this. 

So sorry for any confusion I caused!

**Comment by thediary** [comment]
Hahaha I looked at it and thought that answer seemed a bit out of place! No worries at all ; ) I look forward to the functionality and keep up the great stuff with Smooch!

**Comment by mspensieri** [comment]
You now do this using the `setMessagesButtonShown:` API in v1.1.0
