### ISSUE TITLE
NSAppTransportSecurity

### ISSUE THREAD

**Issue by thediary** [smooch/smooch-helpkit-ios#7]
Hi there,
Upon updating our app, our users began complaining that none of the help desk articles could load (they could be searched, just not viewed). We took a look and realized none of them could be viewed because of a lack of support for NSAppTransportSecurity.

The screenshots below illustrate the problem, and the alert pops up each time one taps an article.

I suppose we could allow NSAllowsArbitraryLoads, but in keeping with modern security practices, the Smooch and Smooch-helpkit SDKs should be updated to support NSAppTransportSecurity—especially as many apps are required to support this now.

Thanks,
Alex

P.S. (The app in question is http://apple.co/1GHorus in case you wish to try it yourselves.)

![img_2909](https://cloud.githubusercontent.com/assets/13370443/13235882/f0cb37aa-d97d-11e5-928a-957e4e00e124.PNG)
![img_2910](https://cloud.githubusercontent.com/assets/13370443/13235883/f12e2482-d97d-11e5-986a-c28cd86140d9.PNG)

**Comment by mspensieri** [comment]
@thediary Unfortunately there isn't much we can do about this, since the content is not hosted on our servers. In order for ATS to allow the load of a web resource, the host server needs to conform to a certain set of security protocols - there is nothing to _support_ on the device side.

For example, if you're using Zendesk links in your recommendations, then it's up to Zendesk to provide the proper level of security on their server. If the content is hosted on your own servers, I would recommend to verify your SSL configuration and make sure it's ATS compliant!
